version: "3.9"

services:
  easy-rider:
    image: easy-rider:latest 
    restart: always
    logging:
      driver: "journald"
    volumes:
      - ./easy-rider/config:/config:ro
      - ./db:/db
    command:
      [ "run-node", ""
      , "--testnet-magic", "1"
      ]
    networks:
      easy_rider:
        ipv4_address: 172.15.238.20

networks:
  easy_rider:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.238.0/24
          gateway: 172.15.238.1
